# Generated by Django 3.2.8 on 2021-10-30 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fullname', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=120, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=120, null=True)),
                ('drug_lic_no', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('tel_no', models.CharField(blank=True, max_length=120, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_logo', models.FileField(blank=True, null=True, upload_to='media')),
                ('business_address', models.CharField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('total_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=300, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('INJECTION', 'INJECTION'), ('TABLETS', 'TABLETS'), ('CAPSULE', 'CAPSULE'), ('SYRUP', 'SYRUP')], max_length=500, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('hsncode', models.CharField(blank=True, max_length=120, null=True)),
                ('pack', models.CharField(blank=True, max_length=120, null=True)),
                ('scm1', models.CharField(blank=True, max_length=120, null=True)),
                ('scm2', models.CharField(blank=True, max_length=120, null=True)),
                ('rate', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('cgst', models.IntegerField()),
                ('sgst', models.IntegerField()),
                ('qty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
                ('product_type', models.CharField(blank=True, choices=[('INJECTION', 'INJECTION'), ('TABLETS', 'TABLETS'), ('CAPSULE', 'CAPSULE'), ('SYRUP', 'SYRUP')], max_length=500, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('hsncode', models.CharField(blank=True, max_length=120, null=True)),
                ('pack', models.CharField(blank=True, max_length=120, null=True)),
                ('scm1', models.CharField(blank=True, max_length=120, null=True)),
                ('scm2', models.CharField(blank=True, max_length=120, null=True)),
                ('rate', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('cgst', models.IntegerField()),
                ('qty', models.IntegerField(default=1)),
                ('amount', models.IntegerField(default=0)),
                ('sgst', models.IntegerField()),
                ('craete_date', models.DateField(auto_now_add=True)),
                ('is_order', models.BooleanField(default=False)),
                ('confirm_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_order', to='api.confirmorder')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
