# Generated by Django 3.2.8 on 2021-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
