# Generated by Django 3.2.8 on 2021-10-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productlist_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
