# Generated by Django 3.2.8 on 2021-10-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211030_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
