# Generated by Django 3.2.8 on 2021-11-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211030_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], max_length=200),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
