# Generated by Django 3.2.8 on 2021-11-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211101_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='cgst',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='sgst',
            field=models.IntegerField(),
        ),
    ]
